# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration file for Calamares (Ubuntu Unattended)
---
modules-search: [ local ]

instances:

- id:       ""
  module:   welcome
  config:   welcome.conf
  autoProceed: true

- id:       before-online
  module:   shellprocess
  config:   shellprocess-before-online.conf

- id:       cleanup_calamares
  module:   shellprocess
  config:   shellprocess_cleanup_calamares.conf

- id:       ""
  module:   locale
  config:   locale.conf
  autoProceed: true

- id:       ""
  module:   keyboard
  config:   keyboard.conf
  autoProceed: true

- id:       ""
  module:   partition
  config:   partition.conf
  autoProceed: true

- id:       ""
  module:   users
  config:   users.conf
  autoProceed: true

- id:       ""
  module:   summary
  config:   summary.conf
  autoProceed: true

- id:       ""
  module:   finished
  config:   finished.conf
  autoProceed: true

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - shellprocess@before-online
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - grubcfg
  - bootloader
  - shellprocess@cleanup_calamares
  - umount
- show:
  - finished

branding: ubuntu

prompt-install: false

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: true

quit-at-end: true
