# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the partition module (Ubuntu Unattended)
---
requiredStorage: 8

efiSystemPartition: "/boot/efi"

efiSystemPartitionSize: 512M

userSwapChoices:
    - none

drawNestedPartitions: false

alwaysShowPartitionLabels: true

initialPartitioningChoice: erase

initialSwapChoice: none

defaultFileSystemType: "ext4"

defaultPartitionTableType: gpt

availableFileSystemTypes: ["ext4", "btrfs", "xfs"]

bootloaderOverrides:
    - name: grub
      efiSystemPartition: "/boot/efi"
      efiSystemPartitionSize: 512M
      initialPartitioningChoice: erase
