# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the users module (Ubuntu Unattended)
---
defaultGroups:
    - sudo
    - adm
    - cdrom
    - dip
    - plugdev
    - users
    - lpadmin
    - sambashare

doAutologin: false

sudoersGroup: sudo

setRootPassword: false

doReusePassword: true

passwordRequirements:
    minLength: 4

allowWeakPasswords: true
allowWeakPasswordsDefault: true

user:
  shell: /bin/bash
  forbidden_names:
    - root
    - adm
    - bin
    - daemon
    - dbus
    - games
    - halt
    - lp
    - mail
    - man
    - news
    - nobody
    - sync
    - sys
    - systemd-coredump
    - systemd-network
    - systemd-resolve
    - systemd-timesync
  home_permissions: "o700"

hostname:
  location: EtcFile
  writeHostsFile: true
  template: "ubuntu-${cpu}"
  forbidden_names: [ localhost ]

allowActiveDirectory: false

platform:
    desktop:
        presets:
            fullName:
                value: "Test Child"
                editable: true
            loginName:
                value: "testchild"
                editable: true
