#!/usr/bin/env bash
set -euo pipefail

lb config noauto \
  --mode ubuntu \
  --distribution jammy \
  --archive-areas "main restricted universe multiverse" \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --zsync false \
  --initramfs live-boot \
  --initsystem systemd \
  --syslinux-theme live-build \
  --bootappend-live "boot=live components username=child hostname=parental-os" \
  "${@}"
